"use strict";

const { CATEGORY_META } = require("../utils/sinks");

const BOX = {
  branch:  "├── ",
  last:    "└── ",
  vert:    "│   ",
  empty:   "    ",
  recurse: "↩",
};

function formatReport(result, config) {
  const { graph, stats, files, parseErrors } = result;
  const out = [];

  out.push("# Call Graph Report");
  out.push("");
  out.push(`_Generated by **calltree-pro** on ${new Date().toISOString()}_`);
  out.push("");

  out.push("## ▣ Summary");
  out.push("");
  out.push("| Metric | Value |");
  out.push("|---|---:|");
  out.push(`| Files analyzed     | ${stats.fileCount} |`);
  out.push(`| Functions found    | ${stats.functionCount} |`);
  out.push(`| Call edges         | ${stats.callCount} |`);
  out.push(`| Parse errors       | ${stats.parseErrors} |`);
  out.push(`| Unresolved fillers | ${countUnresolved(graph)} |`);
  out.push("");

  out.push("## ▤ Files");
  out.push("");
  for (const f of files) out.push(`- \`${f}\``);
  out.push("");

  out.push("## ⚠ Sinks by category");
  out.push("");
  out.push("Sinks are categorized API touchpoints relevant to security/reverse-engineering analysis.");
  out.push("");
  const groups = graph.byCategory();
  const order = [
    "dynamic_exec", "child_process", "network", "dns",
    "fs", "env", "crypto", "encoding", "fingerprint",
    "scheduling", "dom", "control", "error",
  ];
  out.push("| Category | Icon | Count | Functions |");
  out.push("|---|:-:|---:|---|");
  for (const cat of order) {
    if (!groups[cat] || !groups[cat].length) continue;
    const meta = CATEGORY_META[cat];
    const names = groups[cat]
      .slice(0, 8)
      .map((i) => `\`${i.name}\``)
      .join(", ");
    const more = groups[cat].length > 8 ? ` _(+${groups[cat].length - 8} more)_` : "";
    out.push(`| **${meta.label}** | ${meta.icon} | ${groups[cat].length} | ${names}${more} |`);
  }
  out.push("");

  const roots = graph.roots();
  out.push(`## ⌂ Roots (entry points) — ${roots.length}`);
  out.push("");
  for (const r of roots) {
    const info = graph.functions.get(r);
    const tag = info?.unresolved ? " _(unresolved)_" : "";
    out.push(`- \`${r}\`${tag}`);
  }
  out.push("");

  out.push("## 🌳 Call trees");
  out.push("");
  out.push("Each entry point's call tree is rendered below. Recursive references are marked with `↩`. Unresolved callees (no definition found in source — common with obfuscated code) are tagged `[unresolved]`.");
  out.push("");

  // Filter trees: skip top-level filler-only roots that are noise
  const meaningful = roots.filter((r) => {
    if (r.startsWith("<anonymous@") && !graph.forward.has(r)) return false;
    return true;
  });

  for (const root of meaningful) {
    out.push(`### \`${root}\``);
    out.push("");
    out.push("```");
    const lines = [];
    renderMdTree(graph, root, "", true, true, new Set(), config, lines);
    out.push(...lines);
    out.push("```");
    out.push("");
  }

  out.push(`## ◉ Hotspots — top ${config.hotspots || 15}`);
  out.push("");
  const hot = graph.hotspots(config.hotspots || 15);
  out.push("| Rank | Function | Calls | Category | Bar |");
  out.push("|---:|---|---:|---|---|");
  const max = hot[0]?.count || 1;
  hot.forEach((h, i) => {
    const info = graph.functions.get(h.name);
    const cat = info?.category || "unknown";
    const meta = CATEGORY_META[cat] || CATEGORY_META.unknown;
    const bar = "█".repeat(Math.max(1, Math.round((h.count / max) * 18)));
    out.push(
      `| ${i + 1} | \`${escMd(h.name)}\` | ${h.count} | ${meta.icon} ${meta.label} | \`${bar}\` |`,
    );
  });
  out.push("");

  out.push("## ↻ Cycles");
  out.push("");
  const cycles = graph.cycles();
  if (!cycles.length) out.push("_No cycles detected._");
  else for (const cyc of cycles) {
    out.push(`- ${cyc.map((n) => `\`${n}\``).join(" → ")}`);
  }
  out.push("");

  out.push("## ✗ Possibly dead functions");
  out.push("");
  const dead = graph
    .deadFunctions()
    .filter((n) => !roots.includes(n) && !n.startsWith("<top-level"));
  if (!dead.length) out.push("_None._");
  else for (const d of dead) out.push(`- \`${d}\``);
  out.push("");

  out.push("## ⇉ Shortest path to dangerous sinks");
  out.push("");
  out.push("For each entry point, the shortest call chain that reaches a `dynamic_exec`, `child_process`, `network`, or `dns` sink.");
  out.push("");
  const dangerCats = ["dynamic_exec", "child_process", "network", "dns"];
  let foundAny = false;
  for (const root of roots) {
    const path = graph.shortestPathToCategory(root, dangerCats);
    if (!path) continue;
    foundAny = true;
    const sink = path[path.length - 1];
    const cat = graph.functions.get(sink)?.category || "unknown";
    const meta = CATEGORY_META[cat];
    out.push(`- **${meta.icon} ${meta.label}** \`${root}\` → ` +
      path.slice(1).map((n) => `\`${n}\``).join(" → "));
  }
  if (!foundAny) out.push("_No paths to dangerous sinks found._");
  out.push("");

  out.push("## ⚖ Function metrics");
  out.push("");
  out.push("| Function | Kind | Async | LOC | Cx | Callers | Callees | Category |");
  out.push("|---|---|:-:|---:|---:|---:|---:|---|");
  const sortedFns = [...graph.functions.entries()]
    .filter(([, info]) => !info.unresolved)
    .sort((a, b) => (b[1].complexity || 0) - (a[1].complexity || 0));
  for (const [name, info] of sortedFns) {
    const callers = graph.reverse.get(name)?.size || 0;
    const callees = graph.forward.get(name)?.size || 0;
    const cat = info.category || "user";
    const meta = CATEGORY_META[cat] || CATEGORY_META.user;
    out.push(
      `| \`${escMd(name)}\` | ${info.kind} | ${info.isAsync ? "✓" : ""} | ${info.loc} | ${info.complexity} | ${callers} | ${callees} | ${meta.icon} ${meta.label} |`,
    );
  }
  out.push("");

  const unresolved = [...graph.functions.values()].filter((i) => i.unresolved);
  if (unresolved.length) {
    out.push(`## ? Unresolved callees — ${unresolved.length}`);
    out.push("");
    out.push("These names appear as callees but no matching definition was found. Normal for cross-file calls, builtins, and dynamic indirection (e.g. obfuscator.io output). Each is registered as a filler stub so the call tree stays connected.");
    out.push("");
    out.push("| Name | Category | Callers |");
    out.push("|---|---|---:|");
    unresolved
      .sort((a, b) => (graph.reverse.get(b.name)?.size || 0) - (graph.reverse.get(a.name)?.size || 0))
      .forEach((info) => {
        const callers = graph.reverse.get(info.name)?.size || 0;
        const cat = info.category || "unknown";
        const meta = CATEGORY_META[cat] || CATEGORY_META.unknown;
        out.push(`| \`${escMd(info.name)}\` | ${meta.icon} ${meta.label} | ${callers} |`);
      });
    out.push("");
  }

  if (parseErrors.length) {
    out.push("## ! Parse errors");
    out.push("");
    for (const err of parseErrors) {
      out.push(`- \`${err.file}\`: ${err.message}`);
    }
    out.push("");
  }

  return out.join("\n");
}

function renderMdTree(graph, name, prefix, isLast, isRoot, visited, config, out) {
  const maxDepth = config.maxDepth ?? Infinity;
  if (prefix.length / 4 > maxDepth) {
    out.push(prefix + (isLast ? BOX.last : BOX.branch) + "… (max depth)");
    return;
  }
  const resolved = graph.resolve(name) || name;
  const connector = isRoot ? "" : (isLast ? BOX.last : BOX.branch);
  const nextPrefix = isRoot ? "" : prefix + (isLast ? BOX.empty : BOX.vert);

  if (visited.has(resolved)) {
    out.push(prefix + connector + BOX.recurse + " " + resolved);
    return;
  }

  out.push(prefix + connector + plainDecorate(graph, resolved));

  const callees = graph.forward.get(resolved);
  if (!callees) return;

  visited.add(resolved);
  const sorted = [...callees.keys()].sort();
  sorted.forEach((callee, i) => {
    const last = i === sorted.length - 1;
    renderMdTree(
      graph, callee, nextPrefix, last, false,
      new Set(visited), config, out,
    );
  });
}

function plainDecorate(graph, name) {
  const info = graph.functions.get(name);
  if (!info) return name;
  const tags = [];
  if (info.unresolved) tags.push("unresolved");
  if (info.isAsync) tags.push("async");
  if (info.isGenerator) tags.push("gen");
  if (info.isPrivate) tags.push("private");
  if (info.kind === "constructor") tags.push("ctor");
  const cat = info.category;
  if (cat && cat !== "user" && cat !== "unknown") tags.push(cat);
  return name + (tags.length ? `  [${tags.join(",")}]` : "");
}

function countUnresolved(graph) {
  let n = 0;
  for (const info of graph.functions.values()) if (info.unresolved) n++;
  return n;
}

function escMd(s) {
  return s.replace(/\|/g, "\\|");
}

module.exports = { formatReport };
